Update to branch before adding detection module
tomasstolker/pycrires pull request #10
Opened 2023-03-21 14:50 UTC by ricolandman

Finally found the time to add all changes properly. What I added:
- obs_nodding_irregular: Function that works for any nodding sequence (I needed this for my own transit observations). I wanted to implement this within obs_nodding but can't think of a simple way to do it. Right now it is a lot of duplicate code, so could definitely be improved in the future.
- util_extract_science: Function that extracts the results from obs_nodding for specific slit_fraction (e.g. for widely separated planets).
- 2nd order wavelength correction. This "grid search" is quite memory intensive, so I run "correct_wavelengths" multiple times with decreasing accuracy to make it feasible.
- Changed initial guess in fit_gaussian to make the function also works when the star is not in the center.
- custom_extract_2d: Including correction for slit tilt. This makes sure the wavelength solution is consistent vertically, so that we can sum over the spatial dimension in correct_wavelengths_2d.
- obs_nodding: Added the option "check_existing" if you want to skip already reduced files.

I tested it on the beta Pic data and some transit observations and it all runs smooth, but can't guarantee that there are no bugs. Feel free to change stuff or let me know if you want things changed. I have started on the detection module, which should come soon.

2023-03-22 09:58 UTC, ricolandman commented
Oops, I see I messed up the branches. This actually already includes the functions for planet detection:
- remove_starlight: Function for removing the stellar contribution from each row
- remove_pca: Function for removing PCA components for each row
- cross_correlate: Function for cross-correlation.

While these functions are definitely not optimized (I can get a much higher S/N detection with my custom method) you should be able to detect e.g. beta Pic b quite easily using these functions.

2023-03-24 14:02 UTC, tomasstolker requested changes
Amazing work!! Many thanks @ricolandman!

I tested the new methods and it runs all fine. I did not check all the code in detail but from what I can tell it all looks good! Just added a few minor comments. The only larger request that I would have is to add some brief docstrings to the `util` functions if you have the time for that.

Does the new `obs_nodding_irregular` method also work on a regular/ABBA nodding pattern? If so then feel free to remove the old `obs_nodding` and use `obs_nodding_irregular` as the new `obs_nodding` 👍.

Let me know in case you have any questions!

2023-03-28 09:09 UTC, tomasstolker commented
Thanks a lot for the additional improvements!

The checks are not passing. I think because the `requirements.txt` may not be complete?

2023-03-28 09:14 UTC, ricolandman commented on pycrires/util.py
> +def lowpass_filter(flux, window_length):
Done

2023-03-28 09:14 UTC, ricolandman commented on pycrires/pipeline.py
> +                plt.savefig(f"{output_dir}/correlation_map_{nod_ab}_{accuracy}.png")
Done

2023-03-28 09:14 UTC, ricolandman commented on pycrires/pipeline.py
> +    def remove_pca(
Done

2023-03-28 09:14 UTC, ricolandman commented on pycrires/pipeline.py
> +                    print(opt_b, opt_a, opt_c)
Yes

2023-03-28 09:15 UTC, ricolandman commented on pycrires/pipeline.py
> +                    print(f"Removing starlight for detector {det_idx}"
Done

2023-03-28 09:16 UTC, tomasstolker commented on pycrires/util.py
> +    import wget
Okay no worries, I can have a look separately from this PR.

2023-03-28 09:48 UTC, ricolandman commented on pycrires/pipeline.py
> +        sum_over_time: bool = True,
Done

2023-03-28 09:58 UTC, ricolandman commented on pycrires/pipeline.py
> +        import glob
Done

2023-03-28 09:58 UTC, ricolandman commented on pycrires/pipeline.py
> +                            print("WARNING: Not enough telluric features to correct wavelength"
Done

2023-03-28 12:59 UTC, tomasstolker approved these changes
Thanks again for all your work @ricolandman! The PR seems ready to be merged 🎉

2023-03-28 12:59 UTC, merged